src/main/static/src/components/henkilo/AdminViewContainer.js
src/main/static/src/components/henkilo/OppijaViewContainer.js
src/main/static/src/components/henkilo/VirkailijaViewContainer.js
src/main/static/src/components/henkilohaku/HenkilohakuPage.js
src/main/static/src/components/kayttooikeusryhmat/listaus/KayttooikeusryhmaTiedot.js

- Mahdollistaa henkilöiden ja käyttöoikeusryhmien avaamisen uudelle välilehdelle
- Korjaa selaimen takaisin-napin henkilösivuilla

KJHH-1192: Navigoinnin parannuksia

---

src/main/static/src/components/henkilo/OppijaCreateDuplikaatit.js
src/main/static/src/components/henkilo/duplikaatit/DuplikaatitContainer.js
src/main/static/src/components/henkilo/duplikaatit/DuplikaatitPage.js
src/main/static/src/components/henkilo/duplikaatit/DuplikaatitPerson.js
src/main/static/src/components/henkilo/duplikaatit/HenkiloViewDuplikaatit.js

- Muuttaa duplikaattinäkymän linkit osoittamaan näkymän tai henkilön tyypin mukaiseen paikkaan

KJHH-1171: Duplikaattinäkymän linkit

---

src/main/static/src/components/common/henkilo/labelvalues/LinkitetytHenkilot.js
src/main/static/src/components/common/henkilo/labelvalues/MasterHenkilo.js

Lisätään uusia rekisterinpitäjärooleja

KJHH-1335: Add new rekisterinpitaja roles

---

pom.xml
src/main/static/package-lock.json
src/main/static/package.json
src/main/static/src/components/henkilo/AdminViewContainer.js
src/main/static/src/components/henkilo/VirkailijaViewContainer.js

Korjaa henkilölinkitysten linkit

---

src/main/static/src/components/henkilo/duplikaatit/DuplikaatitPerson.js

Atarusta pitää tuoda saman niminen branch tuotantoon samalla että toimii.

Show multiple nationalities for ataru applications.

---

src/main/static/src/components/navigation/TopNavigation.js
src/main/static/src/components/navigation/navigation.utils.js
src/main/static/src/routes.js

Korjaa oppijanavin

---

src/main/resources/Messages_fi.properties
src/main/static/src/actions/henkilo.actions.js
src/main/static/src/components/common/henkilo/labelvalues/Sukupuoli.js
src/main/static/src/components/common/henkilo/labelvalues/Syntymaaika.js

Lisää virheilmoituksen jos hetu on jo käytössä

---

src/main/static/src/components/common/henkilo/usercontent/AdminUserContent.js
src/main/static/src/components/common/henkilo/usercontent/OmattiedotUserContent.js
src/main/static/src/components/common/henkilo/usercontent/PalveluUserContent.js
src/main/static/src/components/common/henkilo/usercontent/VirkailijaUserContent.js

Käyttäjätunnus on pakollinen kenttä kannassa joten salasanan voi
asettaa vain jos käyttäjällä on käyttäjätunnus asetettuna.
KJHH-1491

Disabloi salasana-kenttä jos käyttäjätunnus puuttuu

---

src/main/resources/Messages_fi.properties
src/main/static/src/components/common/select/OrganisaatioSelect.css
src/main/static/src/components/common/select/OrganisaatioSelect.js

Lisää lakkautetut organisaatiot rekisterinpitäjälle

---

pom.xml
src/main/java/fi/vm/sade/henkiloui/configurations/AccessLogConfiguration.java
src/main/java/fi/vm/sade/henkiloui/configurations/ServletContainerConfiguration.java
src/main/resources/application.yml

- Aiemmin oikeuksia vaativat actuatorit ovat nyt oletuksena disabloitu

KJHH-1543: Update to spring-boot 2.1.1.

---

src/main/static/src/components/anomus/HaetutKayttooikeusRyhmatHakuForm.js
src/main/static/src/components/common/henkilo/HenkiloViewCreateKayttooikeusanomus.js
src/main/static/src/components/common/henkilo/createkayttooikeus/CKKohde.js
src/main/static/src/components/common/select/KayttooikeusryhmaSingleSelect.js
src/main/static/src/components/common/select/RyhmaSelection.js
src/main/static/src/components/henkilohaku/HenkilohakuFilters.js
src/main/static/src/reducers/omattiedot.reducer.js
src/main/static/src/utilities/organisaatio.util.js

- Lisää sorttauksen pudotusvalikkoihin
- Poistaa omien organisaatiotietojen indeksointi turhana (ja raskaana) operaationa

KJHH-1566: Sort various dropdown menus. 

---

src/main/static/package-lock.json
src/main/static/src/components/common/henkilo/labelvalues/Sukupuoli.js
src/main/static/src/components/common/henkilo/usercontent/OppijaUserContent.js
src/main/static/src/components/common/henkilo/usercontent/VirkailijaUserContent.js
src/main/static/src/components/henkilo/AdminViewContainer.js
src/main/static/src/components/henkilo/VirkailijaViewContainer.js
src/main/static/src/components/omattiedot/OmattiedotPageContainer.js
src/main/static/src/reducers/koodisto.reducer.js

- Muuttaa Sukupuoli komponentin hakemaan itse kansalaisuuskoodiston kun komponentti ladataan. Tämä korjaa kansalaisuuden näkymisen oppija näkymässä.

KJHH-1578: oppija nakyma kansalaisuus

---

src/main/static/package-lock.json
src/main/static/src/components/common/henkilo/labelvalues/AnomusIlmoitus.js
src/main/static/src/components/common/henkilo/usercontent/OmattiedotUserContent.js
src/main/static/src/henkilo-ui-virkailija-oph.js

- Rekisterinpitäjälle tilaus anomusilmoituksiin käyttöoikeusryhmäkohtaisesti

KJHH-823 anomus ilmoitus

---

src/main/resources/Messages_fi.properties
src/main/static/package-lock.json
src/main/static/package.json
src/main/static/src/components/navigation/TopNavigation.js
src/main/static/src/containers/App.js
src/main/static/src/flow-type-helper/moment-types.js
src/main/static/src/localizabletext.js

- Antaa varoituksen jos sivu avataan muulla asiointikielellä kuin suomi tai ruotsi
- Korjaa käyttöoikeusryhmän muokkaussivun kaatumisen muulla asiointikielellä kuin suomi tai ruotsi

KJHH-1553: en locale

---

src/main/static/src/components/common/henkilo/usercontent/AdminUserContent.js

Vain olemassa olevan käyttäjätunnuksen muokkaaminen on sallittu.
KJHH-1614

Lisää käyttäjätunnuksen lisäämisen estämisen

---

src/main/static/src/index.js

(cherry picked from commit 8fd0f4b)

OK-241 use oph-urls-js from OK-241__caller-id branch

---

src/main/static/src/components/henkilo/duplikaatit/DuplikaatitContainer.js
src/main/static/src/components/henkilo/duplikaatit/HenkiloViewDuplikaatit.js
src/main/static/src/components/navigation/NavigationTabs.js
src/main/static/src/reducers/henkilo.reducer.js

Disabloi duplikaattinäkymä palvelukäyttäjiltä

---

src/main/resources/Messages_fi.properties
src/main/static/src/components/kutsuminen/KutsuConfirmation.js

Validointi poistui käyttöoikeuspalvelusta.
KJHH-1697

Poistaa kutsun virheilmoituksen

---

src/main/static/src/components/henkilo/duplikaatit/DuplikaatitPerson.js

Link AtaruHakemus to page which shows the application directly instead of first loading all possible applications and then showing just the one user is interested of

BUG-2124: direct link for ataruhakemus

---

src/main/static/src/components/common/henkilo/AccessRightDetails.css
src/main/static/src/components/common/henkilo/AccessRightDetails.test.ts
src/main/static/src/components/common/henkilo/AccessRightDetails.tsx
src/main/static/src/components/common/henkilo/HenkiloViewExistingKayttooikeus.tsx
src/main/static/src/components/common/henkilo/HenkiloViewExpiredKayttooikeus.tsx
src/main/static/src/components/common/henkilo/HenkiloViewOpenKayttooikeusanomus.tsx
src/main/static/src/components/common/modal/OphModal.tsx
src/main/static/src/components/common/table/Table.tsx
src/main/static/src/utilities/localisation.util.test.ts
src/main/static/src/utilities/localisation.util.ts

Note: dependes from: https://github.com/Opetushallitus/kayttooikeus/pull/279

KJHH-1655: Add access right group description popup in person pages

---

src/main/static/src/components/common/henkilo/HenkiloViewCreateKayttooikeusanomus.tsx

- Show success notification
- Hide form instructions by default

KJHH-2035: Improve access right request creation UI

---

src/main/static/src/components/common/henkilo/HenkiloViewContactContent.test.ts
src/main/static/src/components/common/henkilo/HenkiloViewContactContent.tsx

* Each public servant should have at least one work email address
defined.

KJHH-2065: Prevent removing of last work email address

---

src/main/static/src/components/sahkopostivarmennus/EmailVerificationContainer.tsx
src/main/static/src/components/sahkopostivarmennus/EmailVerificationList.tsx
src/main/static/src/components/sahkopostivarmennus/EmailVerificationPage.tsx
src/main/static/src/utilities/yhteystietoryhma.util.test.ts
src/main/static/src/utilities/yhteystietoryhma.util.ts

* Do not allow empty value, e.g. disable button
* Add error notifications on backend errors

KJHH-2097: Improve email verification validation

---

README.md
src/main/static/src/components/common/table/Table.tsx
src/main/static/src/components/reports/accessrights/AccessRightsReport.tsx
src/main/static/src/components/reports/accessrights/AccessRightsReportData.test.tsx
src/main/static/src/components/reports/accessrights/AccessRightsReportData.tsx
src/main/static/src/components/reports/accessrights/__snapshots__/AccessRightsReportData.test.tsx.snap

* Possible workaround for browser crash with large datasets

KJHH-2184: Add paging support for access right reports result table

---

src/main/static/src/components/oppijoidentuonti/TuontiKoosteTable.tsx

* Name as link to user details

KJHH-2236: Add service user details to tuontikooste
